version: '3'
services:
  kafka1:
    restart: always
    container_name: kafka1
    image: confluentinc/cp-kafka
    ports:
      - '29091:29091'
      - '39091:39091'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: '<zookeper1-ip>:<zookeper1-port>,<zookeper2-ip>:<zookeper2-port>'
      KAFKA_LISTENERS: INTERNAL://kafka1:39091,EXTERNAL://kafka1:29091
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://<ip-vm>:39091,EXTERNAL://<ip-vm>:29091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    mem_limit: 1.2g
